export default {
  CHANGE_CITY_FILTER: 'CHANGE_CITY_FILTER',
  CHANGE_OWNER_FILTER: 'CHANGE_OWNER_FILTER',
  CHANGE_POSTAL_CODE_FILTER: 'CHANGE_POSTAL_CODE_FILTER',
  GET_UNITS_ERROR: 'GET_UNITS_ERROR',
  GET_UNITS_REQUEST: 'GET_UNITS_REQUEST',
  GET_UNITS_SUCCESS: 'GET_UNITS_SUCCESS',
};
