export default {
  CHANGE_CITY_FILTER: 'CHANGE_CITY_FILTER',
  CHANGE_MESSAGE: 'CHANGE_MESSAGE',
  GET_UNITS_ERROR: 'GET_UNITS_ERROR',
  GET_UNITS_REQUEST: 'GET_UNITS_REQUEST',
  GET_UNITS_SUCCESS: 'GET_UNITS_SUCCESS',
};
